# Generated by Django 2.2.6 on 2019-12-15 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('phone', models.CharField(default=0, max_length=20)),
                ('skill', models.TextField()),
            ],
        ),
    ]
